require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  Exclude:
    - 'lib/rubocop/cop/gitlab_security/*.rb'
    - 'spec/rubocop/cop/gitlab_security/*.rb'
Naming/FileName:
  Exclude:
    - lib/rubocop-eightyfourcodes.rb
RSpec/ExampleLength:
  Max: 10
